version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      # Break things up into a few steps to try to reduce the frequency of OOMs
      - run: ./gradlew :kotlin:semlang-project-euler:build --max-workers=1
      - run: ./gradlew :kotlin:semlang-java-writer:build --max-workers=1
      - run: ./gradlew build --max-workers=1
      - run:
          command: |
            mkdir -p circle-test-results/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} circle-test-results/junit/ \;
            mkdir -p circle-test-results/jest/
            find . -type f -regex ".*/build/test-results/jest/.*xml" -exec cp {} circle-test-results/jest/ \;
          when: always
      - store_test_results:
          path: circle-test-results

workflows:
  version: 2
  build:
    jobs:
      - build
